/**
 * Intune Configuration Profile generator for the DO simulator.
 *
 * Produces a Settings Catalog / OMA-URI payload with the recommended
 * Delivery Optimization settings, ready to deploy via the standard
 * `create_compliance_policy`-style flow.
 *
 * Reference: ./Vendor/MSFT/Policy/Config/DeliveryOptimization in the
 * Windows MDM CSP (Windows 10/11).
 */

import type { DOIntuneProfile, DOSimulationResult, DOSiteRecommendation } from "@intune-agent/shared";

/**
 * Build a profile that targets a specific site (one profile per site is the
 * recommended pattern because DOGroupId is per-site). The caller can
 * materialise N profiles by iterating perSite.
 */
export function buildIntuneProfileForSite(
  result: DOSimulationResult,
  rec: DOSiteRecommendation
): DOIntuneProfile {
  const settings: DOIntuneProfile["settings"] = [
    {
      omaUri: "./Vendor/MSFT/Policy/Config/DeliveryOptimization/DODownloadMode",
      name: "DODownloadMode",
      description: rec.downloadModeName,
      dataType: "int",
      value: rec.downloadMode,
    },
    {
      omaUri: "./Vendor/MSFT/Policy/Config/DeliveryOptimization/DOGroupIdSource",
      name: "DOGroupIdSource",
      description: "How clients determine their DO group (1=AD site, 4=DNS suffix, 5=GroupId)",
      dataType: "int",
      value: rec.doGroupIdSource,
    },
  ];

  // Only emit DOGroupId when the source is the explicit GUID source.
  if (rec.doGroupIdSource === 5) {
    settings.push({
      omaUri: "./Vendor/MSFT/Policy/Config/DeliveryOptimization/DOGroupId",
      name: "DOGroupId",
      description: "Stable DO group GUID for this site",
      dataType: "string",
      value: rec.doGroupId,
    });
  }

  // Common best-practice settings — derived from site profile
  settings.push(
    {
      omaUri: "./Vendor/MSFT/Policy/Config/DeliveryOptimization/DOPercentageMaxBackgroundBandwidth",
      name: "DOPercentageMaxBackgroundBandwidth",
      description: "% of WAN bandwidth DO may use in background",
      dataType: "int",
      value: 50,
    },
    {
      omaUri: "./Vendor/MSFT/Policy/Config/DeliveryOptimization/DOPercentageMaxForegroundBandwidth",
      name: "DOPercentageMaxForegroundBandwidth",
      description: "% of WAN bandwidth DO may use in foreground",
      dataType: "int",
      value: 75,
    },
    {
      omaUri: "./Vendor/MSFT/Policy/Config/DeliveryOptimization/DOMinDiskSizeAllowedToPeer",
      name: "DOMinDiskSizeAllowedToPeer",
      description: "Devices below this disk size (GB) won't seed peers",
      dataType: "int",
      value: 64,
    },
    {
      omaUri: "./Vendor/MSFT/Policy/Config/DeliveryOptimization/DOMaxCacheAge",
      name: "DOMaxCacheAge",
      description: "DO cache age in seconds (default 259200 = 3 days)",
      dataType: "int",
      value: 259200,
    }
  );

  if (rec.deployMCC) {
    // Note: the actual MCC hostname is set via DOCacheHost — admin must fill in
    // the FQDN of the MCC node deployed at this site.
    settings.push({
      omaUri: "./Vendor/MSFT/Policy/Config/DeliveryOptimization/DOCacheHost",
      name: "DOCacheHost",
      description: "FQDN of the Microsoft Connected Cache server at this site (replace placeholder)",
      dataType: "string",
      value: `mcc.${slug(rec.siteName)}.corp.local`,
    });
  }

  return {
    displayName: `Intune007 — DO — ${rec.siteName}`,
    description: `Auto-generated by Intune007 DO Simulator (${result.name}). Site: ${rec.siteName}, mode ${rec.downloadModeName}.`,
    settings,
  };
}

export function buildAllProfiles(result: DOSimulationResult): DOIntuneProfile[] {
  return result.perSite.map((rec) => buildIntuneProfileForSite(result, rec));
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "site";
}
