import { useState } from "react";
import { useActivityStore } from "../stores/activityStore.ts";
import {
  Loader2,
  FileText,
  Sparkles,
  Download,
  Clock,
  Database,
  RefreshCw,
} from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

interface GeneratedReport {
  title: string;
  prompt: string;
  generatedAt: string;
  durationMs: number;
  dataSources: string[];
  markdown: string;
}

const SOURCE_LABELS: Record<string, string> = {
  devices: "Devices",
  compliance_status: "Compliance Status",
  compliance_policies: "Compliance Policies",
  config_profiles: "Config Profiles",
  apps: "Apps",
  conditional_access: "Conditional Access",
  autopilot: "Autopilot",
  groups: "Groups",
  security: "Security Alerts",
  updates: "Windows Updates",
  remediation: "Remediations",
  audit: "Audit Logs",
  signin: "Sign-In Logs",
  os_breakdown: "OS Distribution",
  stale_devices: "Stale Devices",
};

const TEMPLATES = [
  "Full executive summary of our Intune environment",
  "Compliance report for all Windows devices",
  "Security posture report with alerts and risks",
  "App deployment status across all devices",
  "Stale and inactive devices report",
  "Conditional Access policy review",
  "Windows Update compliance report",
  "Autopilot enrollment status report",
  "Device inventory by OS platform",
  "Monthly IT security report for management",
];

export default function ReportGeneratorPanel() {
  const [prompt, setPrompt] = useState("");
  const [report, setReport] = useState<GeneratedReport | null>(null);
  const [history, setHistory] = useState<GeneratedReport[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generate = async () => {
    if (!prompt.trim() || isGenerating) return;
    setIsGenerating(true);
    setError(null);
    setReport(null);
    useActivityStore.getState().addActivity("report-generation");
    try {
      const res = await fetch("/api/report-generator/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: prompt.trim() }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setReport(data);
      setHistory((prev) => [data, ...prev]);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setIsGenerating(false);
      useActivityStore.getState().removeActivity("report-generation");
    }
  };

  const exportReport = () => {
    if (!report) return;
    const blob = new Blob([report.markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.title.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportHtml = () => {
    if (!report) return;
    const el = document.querySelector(".report-content");
    if (!el) return;
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${report.title}</title><style>body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;max-width:900px;margin:40px auto;padding:0 20px;color:#1a1a1a;line-height:1.6}table{border-collapse:collapse;width:100%;margin:1em 0}th,td{border:1px solid #ddd;padding:8px;text-align:left}th{background:#f5f5f5;font-weight:600}tr:nth-child(even){background:#fafafa}h1,h2,h3{color:#1a365d}code{background:#f0f0f0;padding:2px 6px;border-radius:3px;font-size:0.9em}</style></head><body>${el.innerHTML}<footer style="margin-top:40px;padding-top:20px;border-top:1px solid #ddd;color:#666;font-size:0.85em"><p>Generated by Intune007 on ${new Date(report.generatedAt).toLocaleString()}</p></footer></body></html>`;
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.title.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}-${new Date().toISOString().slice(0, 10)}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center gap-2 px-5 py-3 border-b border-gray-800">
        <FileText size={16} className="text-brand-400" />
        <h2 className="text-sm font-semibold text-gray-200">Report Generator</h2>
        <span className="text-[10px] bg-brand-600/20 text-brand-400 px-1.5 py-0.5 rounded">AI-Powered</span>
      </div>

      <div className="flex-1 overflow-y-auto">
        {/* Input section */}
        <div className="px-5 py-4 border-b border-gray-800">
          <label className="text-xs text-gray-400 font-medium mb-1.5 block">
            Describe the report you need
          </label>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            rows={3}
            placeholder="e.g. Generate a comprehensive compliance report for all Windows devices including policy coverage, non-compliant devices, and update status"
            className="w-full bg-gray-800 text-white text-sm rounded-lg px-3 py-2 border border-gray-700 focus:border-brand-500 focus:outline-none placeholder-gray-500 resize-none"
          />

          {/* Templates */}
          <div className="flex flex-wrap gap-1.5 mt-2">
            {TEMPLATES.map((t) => (
              <button
                key={t}
                onClick={() => setPrompt(t)}
                className="text-[10px] px-2 py-1 rounded-md bg-gray-800 text-gray-400 hover:text-white hover:bg-gray-700 border border-gray-700 transition-colors"
              >
                {t}
              </button>
            ))}
          </div>

          <button
            onClick={generate}
            disabled={!prompt.trim() || isGenerating}
            className="mt-3 flex items-center gap-2 bg-brand-600 hover:bg-brand-700 disabled:bg-gray-700 disabled:text-gray-500 text-white text-sm px-4 py-2 rounded-lg transition-colors"
          >
            {isGenerating ? (
              <>
                <Loader2 size={14} className="animate-spin" />
                Generating report...
              </>
            ) : (
              <>
                <Sparkles size={14} />
                Generate Report
              </>
            )}
          </button>

          {isGenerating && (
            <div className="mt-3 flex items-center gap-3 text-xs text-gray-500">
              <Loader2 size={12} className="animate-spin" />
              Pulling data from Intune APIs and generating report with AI...
            </div>
          )}
        </div>

        {/* Error */}
        {error && (
          <div className="mx-5 mt-4 text-sm text-red-400 bg-red-500/10 border border-red-500/30 rounded-lg px-4 py-3">
            {error}
          </div>
        )}

        {/* Report output */}
        {report && (
          <div className="px-5 py-4">
            {/* Report header */}
            <div className="flex items-center justify-between mb-4">
              <div>
                <h3 className="text-sm font-semibold text-gray-200">{report.title}</h3>
                <div className="flex items-center gap-3 mt-1 text-[10px] text-gray-500">
                  <span className="flex items-center gap-1">
                    <Clock size={10} />
                    {new Date(report.generatedAt).toLocaleString()} · {(report.durationMs / 1000).toFixed(1)}s
                  </span>
                  <span className="flex items-center gap-1">
                    <Database size={10} />
                    {report.dataSources.length} data sources
                  </span>
                </div>
              </div>
              <div className="flex gap-1">
                <button
                  onClick={exportReport}
                  className="flex items-center gap-1 px-2.5 py-1.5 text-xs text-gray-400 hover:text-white hover:bg-gray-700 rounded transition-colors border border-gray-700"
                >
                  <Download size={12} />
                  .md
                </button>
                <button
                  onClick={exportHtml}
                  className="flex items-center gap-1 px-2.5 py-1.5 text-xs text-gray-400 hover:text-white hover:bg-gray-700 rounded transition-colors border border-gray-700"
                >
                  <Download size={12} />
                  .html
                </button>
              </div>
            </div>

            {/* Data sources used */}
            <div className="flex flex-wrap gap-1.5 mb-4">
              {report.dataSources.map((s) => (
                <span key={s} className="text-[10px] px-2 py-0.5 rounded-full bg-brand-500/10 text-brand-400 border border-brand-500/20">
                  {SOURCE_LABELS[s] || s}
                </span>
              ))}
            </div>

            {/* Report content */}
            <div className="report-content bg-gray-800/30 border border-gray-700/40 rounded-xl p-6">
              <div className="chat-markdown text-[13px] text-gray-300 leading-relaxed">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{report.markdown}</ReactMarkdown>
              </div>
            </div>
          </div>
        )}

        {/* Report history */}
        {history.length > 1 && (
          <div className="px-5 pb-4">
            <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">
              Previous Reports ({history.length - 1})
            </h3>
            <div className="space-y-1.5">
              {history.slice(1).map((r, i) => (
                <button
                  key={i}
                  onClick={() => setReport(r)}
                  className="w-full text-left flex items-center gap-2 px-3 py-2 rounded-lg bg-gray-800/30 hover:bg-gray-800/50 border border-gray-700/30 transition-colors"
                >
                  <FileText size={13} className="text-gray-500 shrink-0" />
                  <div className="flex-1 min-w-0">
                    <p className="text-xs text-gray-300 truncate">{r.title}</p>
                    <p className="text-[10px] text-gray-600">{new Date(r.generatedAt).toLocaleString()} · {r.dataSources.length} sources</p>
                  </div>
                </button>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
